steps:
  - name: node:16.17.0
    entrypoint: npm
    args: ["install"]
  - name: node:16.17.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}"
      - "NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=${_NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}"
      - "NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=${_NEXT_PUBLIC_FIREBASE_PRIVATE_KEY}"
      - "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}"
      - "NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${_NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}"
      - "NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=${_NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY}"
      - "NEXT_PUBLIC_GOOGLE_CALENDAR_EMAIL=${_NEXT_PUBLIC_GOOGLE_CALENDAR_EMAIL}"
      - "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}"
      - "NEXTAUTH_URL=${_NEXTAUTH_URL}"
      - "SENDGRID_API_KEY=${_SENDGRID_API_KEY}"
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: gcb-trigger-id=9d2b67c9-abe1-4eb4-b500-bbee52715663
  _TRIGGER_ID: 9d2b67c9-abe1-4eb4-b500-bbee52715663
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: test
  REPO_NAME: bitbybit
  _DEPLOY_REGION: us-west1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - test
